// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW46fyHQ9332mzq1RhPG5lffgfzhI6sV0',
    appId: '1:830685456725:web:3fd7227b81636291dc27dc',
    messagingSenderId: '830685456725',
    projectId: 'my-inventorycontrol-project',
    authDomain: 'my-inventorycontrol-project.firebaseapp.com',
    storageBucket: 'my-inventorycontrol-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwV7WjRcZeZIy-YhGhby_pFYJyNn1Ma9Y',
    appId: '1:830685456725:android:451dc18a5648bfe4dc27dc',
    messagingSenderId: '830685456725',
    projectId: 'my-inventorycontrol-project',
    storageBucket: 'my-inventorycontrol-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU56LQtpkNzyqquLeWcKE504AZCAYF-uw',
    appId: '1:830685456725:ios:04c951b21f1ecf10dc27dc',
    messagingSenderId: '830685456725',
    projectId: 'my-inventorycontrol-project',
    storageBucket: 'my-inventorycontrol-project.firebasestorage.app',
    iosBundleId: 'com.inventorycontrol.app',
  );
}
